### ISSUE TITLE
Directory creation not working in Linux

### ISSUE THREAD

**Issue by corvalanlara** [AnandPilania/php-android-cli#7]
When the app creates the files it doesn't create a proper directory, it just generates individual files with the names of the paths they are supposed to be in,names such as "Project\app\src\main\AndroidManifest.xml". 

Edit: I used the latest release phar file. I think latest changes in your code are not reflected in your latest release.

**Comment by AnandPilania** [comment]
@corvalanlara let me fix it by this evening (IST)

**Comment by AnandPilania** [comment]
@corvalanlara please check the latest release, actually I'm using Windows, so can't test it locally.

Regards

**Comment by corvalanlara** [comment]
Now it works!
